FROM registry.access.redhat.com/ubi9/ubi:latest
ADD kyvernopre /kyvernopre
COPY licenses /licenses
USER 10001

LABEL name="Kyverno" \
      maintainer="Kyverno" \
      vendor="Nirmata" \
      version="v1.8.5" \
      release="v1.8.5" \
      summary="Kubernetes Native Policy Management" \
      description="Kubernetes Native Policy Management" 

ENTRYPOINT ["/kyvernopre"]
